apiVersion: sailoperator.io/v1alpha1
kind: ZTunnel
metadata:
  name: default
spec:
  namespace: ztunnel
  profile: ambient
  values:
    multiCluster:
      clusterName: ${CL_NAME}
    network: ${NET}