apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
  namespace: istio-system
spec:
  version: ${ISTIO_VERSION}
  values:
    global:
      meshID: mesh1
      multiCluster:
        clusterName: ${CL_NAME}
      network: ${NET}
